<?xml version="1.0" encoding="Shift_JIS"?>
<?xml-stylesheet type="text/xsl" href="hoot.xsl"?>
<!DOCTYPE gamelist [
	<!ELEMENT gamelist (game|bind)*>
	<!ATTLIST gamelist date CDATA #IMPLIED>
	<!ELEMENT bind (exts,driver,options?)>
	<!ELEMENT exts (ext)*>
	<!ELEMENT ext (#PCDATA)>
	<!ELEMENT game (name,driver,options?,romlist?,titlelist?)>
	<!ELEMENT name (#PCDATA)>
	<!ELEMENT driver (#PCDATA)>
	<!ATTLIST driver type CDATA #IMPLIED>
	<!ELEMENT options (option)*>
	<!ELEMENT option EMPTY>
	<!ATTLIST option name CDATA #REQUIRED
		 value CDATA #REQUIRED>
	<!ELEMENT romlist (rom)*>
	<!ATTLIST romlist archive CDATA #IMPLIED>
	<!ELEMENT rom (#PCDATA)>
	<!ATTLIST rom type CDATA #REQUIRED
		offset CDATA #IMPLIED>
	<!ELEMENT titlelist (title)*>
	<!ELEMENT title (#PCDATA)>
	<!ATTLIST title code CDATA #REQUIRED
					type CDATA #IMPLIED>
]>
<gamelist date="2001/6/17">
	<bind>
		<exts>
			<ext>pce</ext>
			<ext>hes</ext>
		</exts>
		<driver type="hes">pcengine</driver>
		<options>
		</options>
	</bind>
	<bind>
		<exts>
			<ext>kss</ext>
		</exts>
		<driver type="kss">msx</driver>
		<options>
			<option name="ay_mix" value="0x100"/>
			<option name="sn_mix" value="0x100"/>
			<option name="fmpac_mix" value="0xcc"/>
			<option name="fmunit_mix" value="0xcc"/>
			<option name="scc_mix" value="0xcc"/>
		</options>
	</bind>
	<bind>
		<exts>
			<ext>mdx</ext>
		</exts>
		<driver type="mxdrv">x68k</driver>
		<options>
			<option name="opm_mix" value="0xc0"/>
			<option name="pcm_mix" value="0xf0"/>
		</options>
	</bind>
	<game>
		<name>ZAVAS</name>
		<driver type="zavas">glodia</driver>
		<romlist archive="zavas">
			<rom type="code" offset="0x0000">PATCH</rom>
			<rom type="code" offset="0x0100">DRIVER</rom>
			<rom type="bgm" offset="0x00">MUSIC00</rom>
			<rom type="bgm" offset="0x01">MUSIC01</rom>
			<rom type="bgm" offset="0x02">MUSIC02</rom>
			<rom type="bgm" offset="0x03">MUSIC03</rom>
			<rom type="bgm" offset="0x04">MUSIC04</rom>
			<rom type="bgm" offset="0x05">MUSIC05</rom>
			<rom type="bgm" offset="0x06">MUSIC06</rom>
			<rom type="bgm" offset="0x07">MUSIC07</rom>
			<rom type="bgm" offset="0x08">MUSIC08</rom>
			<rom type="bgm" offset="0x09">MUSIC10</rom>
			<rom type="bgm" offset="0x0a">MUSIC11</rom>
			<rom type="bgm" offset="0x0b">MUSIC12</rom>
			<rom type="bgm" offset="0x0c">MUSIC13</rom>
			<rom type="bgm" offset="0x0d">MUSIC14</rom>
			<rom type="bgm" offset="0x0e">MUSIC15</rom>
			<rom type="bgm" offset="0x0f">MUSIC20</rom>
			<rom type="bgm" offset="0x10">MUSIC21</rom>
			<rom type="bgm" offset="0x11">MUSIC22</rom>
			<rom type="bgm" offset="0x12">MUSIC23</rom>
			<rom type="bgm" offset="0x13">MUSIC24</rom>
			<rom type="bgm" offset="0x14">MUSIC25</rom>
		</romlist>
		<titlelist>
			<title code="0x00">ZAOP01</title>
			<title code="0x01">ZAOP02</title>
			<title code="0x09">ZABG01</title>
			<title code="0x0a">ZABG02</title>
			<title code="0x0b">ZABG03</title>
			<title code="0x0c">ZABG04</title>
			<title code="0x0d">ZABG05</title>
			<title code="0x0e">ZABG06</title>
			<title code="0x0f">ZABG07</title>
			<title code="0x10">ZABG08</title>
			<title code="0x11">ZABG09</title>
			<title code="0x12">ZABG10</title>
			<title code="0x13">ZABG11</title>
			<title code="0x14">ZAOPBG</title>
			<title code="0x02">ZAFIGH</title>
			<title code="0x03">ZAED01</title>
			<title code="0x04">ZAFIT2</title>
			<title code="0x05">ZABIG</title>
			<title code="0x06">ZASHOP</title>
			<title code="0x07">ZACONG</title>
			<title code="0x08">ZAMINA</title>
		</titlelist>
	</game>
	<game>
		<name>XTALSOFT DIGITAL JUKE BOX</name>
		<driver type="xtaljbox">xtalsoft</driver>
		<romlist archive="xtaljbox">
			<rom type="code" offset="0x0000">PATCH</rom>
			<rom type="code" offset="0x2000">DRIVER</rom>
			<rom type="code" offset="0x5000">MUSIC00</rom>
			<rom type="bgm" offset="0x00">MUSIC00</rom>
			<rom type="tone" offset="0x00">TONE00</rom>
			<rom type="bgm" offset="0x01">MUSIC01</rom>
			<rom type="tone" offset="0x01">TONE01</rom>
			<rom type="bgm" offset="0x02">MUSIC02</rom>
			<rom type="tone" offset="0x02">TONE01</rom>
			<rom type="bgm" offset="0x03">MUSIC03</rom>
			<rom type="tone" offset="0x03">TONE01</rom>
			<rom type="bgm" offset="0x04">MUSIC04</rom>
			<rom type="tone" offset="0x04">TONE01</rom>
			<rom type="bgm" offset="0x05">MUSIC05</rom>
			<rom type="tone" offset="0x05">TONE01</rom>
			<rom type="bgm" offset="0x06">MUSIC06</rom>
			<rom type="tone" offset="0x06">TONE01</rom>
			<rom type="bgm" offset="0x07">MUSIC07</rom>
			<rom type="tone" offset="0x07">TONE01</rom>
			<rom type="bgm" offset="0x08">MUSIC08</rom>
			<rom type="tone" offset="0x08">TONE01</rom>
			<rom type="bgm" offset="0x09">MUSIC09</rom>
			<rom type="tone" offset="0x09">TONE01</rom>
			<rom type="bgm" offset="0x0a">MUSIC10</rom>
			<rom type="tone" offset="0x0a">TONE01</rom>
			<rom type="bgm" offset="0x0b">MUSIC11</rom>
			<rom type="tone" offset="0x0b">TONE01</rom>
			<rom type="bgm" offset="0x0c">MUSIC12</rom>
			<rom type="tone" offset="0x0c">TONE02</rom>
			<rom type="bgm" offset="0x0d">MUSIC13</rom>
			<rom type="tone" offset="0x0d">TONE02</rom>
			<rom type="bgm" offset="0x0e">MUSIC14</rom>
			<rom type="tone" offset="0x0e">TONE02</rom>
			<rom type="bgm" offset="0x0f">MUSIC15</rom>
			<rom type="tone" offset="0x0f">TONE02</rom>
			<rom type="bgm" offset="0x10">MUSIC16</rom>
			<rom type="tone" offset="0x10">TONE02</rom>
			<rom type="bgm" offset="0x11">MUSIC17</rom>
			<rom type="tone" offset="0x11">TONE02</rom>
			<rom type="bgm" offset="0x12">MUSIC18</rom>
			<rom type="tone" offset="0x12">TONE02</rom>
			<rom type="bgm" offset="0x13">MUSIC19</rom>
			<rom type="tone" offset="0x13">TONE02</rom>
			<rom type="bgm" offset="0x14">MUSIC20</rom>
			<rom type="tone" offset="0x14">TONE02</rom>
			<rom type="bgm" offset="0x15">MUSIC21</rom>
			<rom type="tone" offset="0x15">TONE02</rom>
			<rom type="bgm" offset="0x16">MUSIC22</rom>
			<rom type="tone" offset="0x16">TONE02</rom>
			<rom type="bgm" offset="0x17">MUSIC23</rom>
			<rom type="tone" offset="0x17">TONE02</rom>
			<rom type="bgm" offset="0x18">MUSIC24</rom>
			<rom type="tone" offset="0x18">TONE02</rom>
			<rom type="bgm" offset="0x19">MUSIC25</rom>
			<rom type="tone" offset="0x19">TONE02</rom>
			<rom type="bgm" offset="0x1a">MUSIC26</rom>
			<rom type="tone" offset="0x1a">TONE02</rom>
			<rom type="bgm" offset="0x1b">MUSIC27</rom>
			<rom type="tone" offset="0x1b">TONE02</rom>
			<rom type="bgm" offset="0x1c">MUSIC28</rom>
			<rom type="tone" offset="0x1c">TONE02</rom>
			<rom type="bgm" offset="0x1d">MUSIC29</rom>
			<rom type="tone" offset="0x1d">TONE02</rom>
			<rom type="bgm" offset="0x1e">MUSIC30</rom>
			<rom type="tone" offset="0x1e">TONE02</rom>
			<rom type="bgm" offset="0x1f">MUSIC31</rom>
			<rom type="tone" offset="0x1f">TONE02</rom>
			<rom type="bgm" offset="0x20">MUSIC32</rom>
			<rom type="tone" offset="0x20">TONE02</rom>
			<rom type="bgm" offset="0x21">MUSIC33</rom>
			<rom type="tone" offset="0x21">TONE02</rom>
			<rom type="bgm" offset="0x22">MUSIC34</rom>
			<rom type="tone" offset="0x22">TONE03</rom>
			<rom type="bgm" offset="0x23">MUSIC35</rom>
			<rom type="tone" offset="0x23">TONE03</rom>
			<rom type="bgm" offset="0x24">MUSIC35</rom>
			<rom type="tone" offset="0x24">TONE03</rom>
			<rom type="bgm" offset="0x25">MUSIC37</rom>
			<rom type="tone" offset="0x25">TONE03</rom>
			<rom type="bgm" offset="0x26">MUSIC38</rom>
			<rom type="tone" offset="0x26">TONE03</rom>
			<rom type="bgm" offset="0x27">MUSIC39</rom>
			<rom type="tone" offset="0x27">TONE03</rom>
			<rom type="bgm" offset="0x28">MUSIC40</rom>
			<rom type="tone" offset="0x28">TONE03</rom>
			<rom type="bgm" offset="0x29">MUSIC41</rom>
			<rom type="tone" offset="0x29">TONE03</rom>
			<rom type="bgm" offset="0x2a">MUSIC42</rom>
			<rom type="tone" offset="0x2a">TONE03</rom>
			<rom type="bgm" offset="0x2b">MUSIC43</rom>
			<rom type="tone" offset="0x2b">TONE03</rom>
			<rom type="bgm" offset="0x2c">MUSIC44</rom>
			<rom type="tone" offset="0x2c">TONE04</rom>
			<rom type="bgm" offset="0x2d">MUSIC45</rom>
			<rom type="tone" offset="0x2d">TONE05</rom>
			<rom type="bgm" offset="0x2e">MUSIC46</rom>
			<rom type="tone" offset="0x2e">TONE06</rom>
			<rom type="bgm" offset="0x2f">MUSIC47</rom>
			<rom type="tone" offset="0x2f">TONE07</rom>
			<rom type="bgm" offset="0x30">MUSIC48</rom>
			<rom type="tone" offset="0x30">TONE08</rom>
			<rom type="bgm" offset="0x31">MUSIC49</rom>
			<rom type="tone" offset="0x31">TONE09</rom>
			<rom type="bgm" offset="0x32">MUSIC50</rom>
			<rom type="tone" offset="0x32">TONE10</rom>
			<rom type="bgm" offset="0x33">MUSIC51</rom>
			<rom type="tone" offset="0x33">TONE11</rom>
			<rom type="bgm" offset="0x34">MUSIC52</rom>
			<rom type="tone" offset="0x34">TONE12</rom>
			<rom type="bgm" offset="0x35">MUSIC53</rom>
			<rom type="tone" offset="0x35">TONE13</rom>
			<rom type="bgm" offset="0x36">MUSIC54</rom>
			<rom type="tone" offset="0x36">TONE14</rom>
			<rom type="bgm" offset="0x37">MUSIC55</rom>
			<rom type="tone" offset="0x37">TONE15</rom>
			<rom type="bgm" offset="0x38">MUSIC56</rom>
			<rom type="tone" offset="0x38">TONE16</rom>
		</romlist>
		<titlelist>
			<title code="0x00">XTALSOFT DIGITAL JUKE BOX</title>
			<title code="0x01">Jehard / Ｊｅｈａｒｄ</title>
			<title code="0x02">Jehard / 忘却街</title>
			<title code="0x03">Jehard / 水魔洞</title>
			<title code="0x04">Jehard / 妖魔洞</title>
			<title code="0x05">Jehard / 魔王</title>
			<title code="0x06">Jehard / 火炎洞</title>
			<title code="0x07">Jehard / 獣神</title>
			<title code="0x08">Jehard / 地下迷宮</title>
			<title code="0x09">Jehard / 渡魂鐘</title>
			<title code="0x0a">Jehard / 魔教会</title>
			<title code="0x0b">Jehard / ＥＮＤＩＮＧ</title>
			<title code="0x0c">クリムゾン / プロローグ</title>
			<title code="0x0d">クリムゾン / 冒険者達</title>
			<title code="0x0e">クリムゾン / 遺跡の谷</title>
			<title code="0x0f">クリムゾン / オーガ・バトル</title>
			<title code="0x10">クリムゾン / エロイア城</title>
			<title code="0x11">クリムゾン / しゃべらずの森</title>
			<title code="0x12">クリムゾン / レクイエム</title>
			<title code="0x13">クリムゾン / インキュバス城</title>
			<title code="0x14">クリムゾン / 魔獣のつり橋</title>
			<title code="0x15">クリムゾン / モグネス山</title>
			<title code="0x16">クリムゾン / 哀しみの町</title>
			<title code="0x17">クリムゾン / 魔物の沼</title>
			<title code="0x18">クリムゾン / 火吹き山</title>
			<title code="0x19">クリムゾン / 死霊の谷</title>
			<title code="0x1a">クリムゾン / キャンプ場</title>
			<title code="0x1b">クリムゾン / 毒の沼</title>
			<title code="0x1c">クリムゾン / 幻の城</title>
			<title code="0x1d">クリムゾン / コダール城</title>
			<title code="0x1e">クリムゾン / クリムゾン城</title>
			<title code="0x1f">クリムゾン / クリムゾン様、永遠に…</title>
			<title code="0x20">クリムゾン / エピローグ</title>
			<title code="0x21">クリムゾン / はるかなる旅立ち（未使用）</title>
			<title code="0x22">Mr.プロ野球 / 開幕</title>
			<title code="0x23">Mr.プロ野球 / 監督就任</title>
			<title code="0x24">Mr.プロ野球 / 応援歌</title>
			<title code="0x25">Mr.プロ野球 / 長い一日</title>
			<title code="0x26">Mr.プロ野球 / ファインプレー</title>
			<title code="0x27">Mr.プロ野球 / 一球入魂</title>
			<title code="0x28">Mr.プロ野球 / 本日の試合結果</title>
			<title code="0x29">Mr.プロ野球 / ＴＯＰ１５</title>
			<title code="0x2a">Mr.プロ野球 / 男達の挽歌</title>
			<title code="0x2b">Mr.プロ野球 / 栄光の讃歌</title>
			<title code="0x2c">BATTLE GORILLA / ＢＡＴＴＬＥ　ＧＯＲＩＬＬＡ</title>
			<title code="0x2d">BATTLE GORILLA / ＴＡＣＴＩＣＳ</title>
			<title code="0x2e">BATTLE GORILLA / ＭＯＲＳＥ</title>
			<title code="0x2f">BATTLE GORILLA / ＳＴＡＲＴＩＮＧ　ＢＡＴＴＬＥ</title>
			<title code="0x30">BATTLE GORILLA / ＢＩＧ　ＳＡＶＡＮＮＡ</title>
			<title code="0x31">BATTLE GORILLA / ＢＡＤ　ＳＴＥＰ</title>
			<title code="0x32">BATTLE GORILLA / ＳＩＬＥＮＴ　ＳＴＲＥＡＭ</title>
			<title code="0x33">BATTLE GORILLA / ＤＥＡＤ　ＲＵＮ</title>
			<title code="0x34">BATTLE GORILLA / ＴＨＵＮＤＥＲ　ＢＬＡＤＥ</title>
			<title code="0x35">BATTLE GORILLA / ＤＥＡＴＨ　ＺＯＮＥ</title>
			<title code="0x36">BATTLE GORILLA / ＦＩＮＡＬ</title>
			<title code="0x37">BATTLE GORILLA / ＲＥＴＵＲＮＥＤ　ＳＯＬＤＩＥＲ</title>
			<title code="0x38">BATTLE GORILLA / ＲＥＳＴ　ＳＯＬＤＩＥＲ　未使用</title>
		</titlelist>
	</game>
	<game>
		<name>BATTLE GORILLA</name>
		<driver type="battlegorilla">xtalsoft</driver>
		<romlist archive="battlegr">
			<rom type="code" offset="0x0000">PATCH</rom>
			<rom type="code" offset="0x3000">DRIVER</rom>
			<rom type="code" offset="0x4400">MUSIC00</rom>
			<rom type="bgm" offset="0x00">MUSIC00</rom>
			<rom type="bgm" offset="0x01">MUSIC01</rom>
			<rom type="bgm" offset="0x02">MUSIC02</rom>
			<rom type="bgm" offset="0x03">MUSIC03</rom>
			<rom type="bgm" offset="0x04">MUSIC04</rom>
			<rom type="bgm" offset="0x05">MUSIC05</rom>
			<rom type="bgm" offset="0x06">MUSIC06</rom>
			<rom type="bgm" offset="0x07">MUSIC07</rom>
			<rom type="bgm" offset="0x08">MUSIC08</rom>
			<rom type="bgm" offset="0x09">MUSIC09</rom>
			<rom type="bgm" offset="0x0a">MUSIC10</rom>
			<rom type="bgm" offset="0x0b">MUSIC11</rom>
			<rom type="bgm" offset="0x0c">MUSIC12</rom>
		</romlist>
		<titlelist>
			<title code="0x00">TACTICS</title>
			<title code="0x01">MORSE</title>
			<title code="0x02">STARTING BATTLE</title>
			<title code="0x03">BIG SAVANNA</title>
			<title code="0x04">BAD STEP</title>
			<title code="0x05">SILENT STREAM</title>
			<title code="0x06">DEAD RUN</title>
			<title code="0x07">THUNDER BLADE</title>
			<title code="0x08">DEATH ZONE</title>
			<title code="0x09">FINAL</title>
			<title code="0x0a">RETURNED SOLDIER</title>
			<title code="0x0b">REST OF SOLDIER/未使用</title>
			<title code="0x0c">BATTLE GORILLA</title>
		</titlelist>
	</game>
	<game>
		<name>ロードモナーク (スピークボード専用体験版)</name>
		<driver type="ed2">mucom88</driver>
		<romlist archive="lmspb">
			<rom type="code" offset="0x4000">PATCH</rom>
			<rom type="code" offset="0x6000">MUSDRV</rom>
			<rom type="bgm" offset="0">FM001.DAT</rom>
			<rom type="bgm" offset="1">FM002.DAT</rom>
			<rom type="bgm" offset="2">FM003.DAT</rom>
			<rom type="bgm" offset="3">FM004.DAT</rom>
			<rom type="bgm" offset="4">FM005.DAT</rom>
			<rom type="bgm" offset="5">FM007.DAT</rom>
			<rom type="bgm" offset="6">FM016.DAT</rom>
			<rom type="bgm" offset="7">FM017.DAT</rom>
			<rom type="bgm" offset="8">FM018.DAT</rom>
			<rom type="bgm" offset="9">FM019.DAT</rom>
			<rom type="bgm" offset="10">FM020.DAT</rom>
			<rom type="bgm" offset="11">FM021.DAT</rom>
		</romlist>
		<titlelist>
			<title code="0">FM001  : プレイヤー勝利</title>
			<title code="1">FM002  : ＧＡＭＥ  ＯＶＥＲ</title>
			<title code="2">FM003  : 表彰式</title>
			<title code="3">FM004  : タイトル</title>
			<title code="4">FM005  : メニュー</title>
			<title code="5">FM007  : マップ エディタ</title>
			<title code="6">FM016  : モナーク（通常）</title>
			<title code="7">FM017  : モナーク（勝利目前）</title>
			<title code="8">FM018  : フーズパニック（通常）</title>
			<title code="9">FM019  : フーズパニック（勝利目前）</title>
			<title code="10">FM020  : 戦国（通常）</title>
			<title code="11">FM021  : 戦国（勝利目前）</title>
		</titlelist>
	</game>
	<game>
		<name>ラグーン (X68000)</name>
		<driver type="generic">x68k</driver>
		<options>
			<option name="opm_mix" value="0xc0"/>
			<option name="pcm_mix" value="0xf0"/>
		</options>
		<romlist archive="lagsnd">
			<rom type="code">zsd.bin</rom>
			<rom type="code" offset="0x10000">opmsong.dat</rom>
			<rom type="code" offset="0x08000">pcmsong.dat</rom>
			<rom type="code" offset="0x05000">soundef.dat</rom>
			<rom type="code" offset="0x20000">adpcm.pcm</rom>
			<rom type="code" offset="0x07000">pcmpat.dat</rom>
			<rom type="code" offset="0x50000">se.pcm</rom>
			<rom type="code" offset="0x06000">tone.dat</rom>
			<rom type="code" offset="0x04000">opmsong.inf</rom>
			<rom type="code" offset="0x04100">soundef.inf</rom>
			<rom type="code" offset="0x04200">adpcm.inf</rom>
			<rom type="code" offset="0x04300">se.inf</rom>
		</romlist>
		<titlelist>
			<title code="0x0100">DESERT PLAINS</title>
			<title code="0x0101">CASTLE SIEGFRID</title>
			<title code="0x0102">MOONCHILD</title>
			<title code="0x0103">ATLAND</title>
			<title code="0x0104">BATTLES OF FATE</title>
			<title code="0x0105">PREMONITION</title>
			<title code="0x0106">VOLOH</title>
			<title code="0x0107">WALKING IN THE SHADOWS</title>
			<title code="0x0108">SENEGUL</title>
			<title code="0x0109">KEEP THE FAITH</title>
			<title code="0x010a">DOMINION</title>
			<title code="0x010b">WHEN DEATH CALL</title>
			<title code="0x010c">DESPERATE DREAMS</title>
			<title code="0x010d">ARMED AND READY</title>
			<title code="0x010e">RUN TO THE HILL OF PHANTOM</title>
			<title code="0x010f">SAY ZOOM!</title>
			<title code="0x0110">UNUSED #1</title>
			<title code="0x0111">SHROUDED MISTERY</title>
			<title code="0x0112">GAME OVER</title>
			<title code="0x0113">VALLEY</title>
			<title code="0x0114">REACH FOR THE SKY</title>
			<title code="0x0115">TOWN OF DESEASE(POPER)</title>
			<title code="0x0116">SHOP</title>
			<title code="0x0117">VOICE OF SPIRITS</title>
			<title code="0x0118">PRINCE OF DARKNESS</title>
			<title code="0x0119">UNUSED #2</title>
			<title code="0x011a">UNUSED #3</title>
			<title code="0x011b">UNUSED #4</title>
			<title code="0x011c">UNUSED #5</title>
			<title code="0x011d">LIVING ON THE EDGE</title>
			<title code="0x011e">TALES FROM THE PEACEFUL WORLD</title>
			<title code="0x011f">ICE CAVE</title>
			<title code="0x0120">UNUSED #6</title>
			<title code="0x0121">UNUSED #7</title>
			<title code="0x0122">CASTLE MARK PHILIPS</title>
			<title code="0x0123">MASTER OF WATER(CASTLE LAGOON)</title>
			<title code="0x0124">UNUSED #8</title>
			<title code="0x0125">LILATY</title>
			<title code="0x0126">UNUSED #9</title>
			<title code="0x0127">ITEM GET</title>
		</titlelist>
	</game>
	<game>
		<name>ジェノサイド (X68000)</name>
		<driver type="generic">x68k</driver>
		<options>
			<option name="opm_mix" value="0xc0"/>
			<option name="pcm_mix" value="0xf0"/>
		</options>
		<romlist archive="gensnd">
			<rom type="code">gnmus.bin</rom>
			<rom type="code" offset="0x10000">opmsong.dat</rom>
			<rom type="code" offset="0x08000">pcmsong.dat</rom>
			<rom type="code" offset="0x05000">soundef.dat</rom>
			<rom type="code" offset="0x20000">adpcm.pcm</rom>
			<rom type="code" offset="0x07000">pcmpat.dat</rom>
			<rom type="code" offset="0x50000">se.pcm</rom>
			<rom type="code" offset="0x06000">tone.dat</rom>
			<rom type="code" offset="0x04000">opmsong.inf</rom>
			<rom type="code" offset="0x04100">soundef.inf</rom>
			<rom type="code" offset="0x04200">adpcm.inf</rom>
			<rom type="code" offset="0x04300">se.inf</rom>
		</romlist>
		<titlelist>
			<title code="0x111">Ceremony</title>
			<title code="0x119">Right Away</title>
			<title code="0x102">Desert Player</title>
			<title code="0x10e">Blast</title>
			<title code="0x105">Burning</title>
			<title code="0x114">Confusion</title>
			<title code="0x100">It's Not Easy</title>
			<title code="0x11a">Splash!</title>
			<title code="0x106">Doom</title>
			<title code="0x10c">Mysticism</title>
			<title code="0x10a">Long Distance</title>
			<title code="0x11d">Before The Storm</title>
			<title code="0x101">On The Run</title>
			<title code="0x113">Symptom</title>
			<title code="0x120">Snare</title>
			<title code="0x11f">Magnificent</title>
			<title code="0x112">Dark Fascination</title>
			<title code="0x110">Bravery</title>
			<title code="0x121">Tensity</title>
			<title code="0x116">Affection</title>
			<title code="0x11c">World Without End</title>
			<title code="0x103">GAME OVER</title>
			<title code="0x10b">ZOOM</title>
			<title code="0x118">Caps</title>
			<title code="0x10f">CONTINUE</title>
			<title code="0x107">GENOCIDE</title>
			<!-- <title code="0x000">Visual demo 0</title> -->
			<!-- <title code="0x000">Visual demo 1</title> -->
			<title code="0x104">Internal 0</title>
			<title code="0x115">Internal 1</title>
			<title code="0x117">Internal 2</title>
			<title code="0x108">BGM #108</title>
			<title code="0x109">BGM #109</title>
			<title code="0x10d">BGM #10d</title>
			<title code="0x11b">BGM #11b</title>
			<title code="0x11e">BGM #11e</title>
			<title code="0x122">BGM #122</title>
		</titlelist>
	</game>
	<game>
		<name>ドラゴンスピリット (X68000)</name>
		<driver type="generic">x68k</driver>
		<options>
			<option name="opm_mix" value="0xc0"/>
			<option name="pcm_mix" value="0xf0"/>
		</options>
		<romlist archive="ds68snd">
			<rom type="code">dsopmdrv.bin</rom>
			<rom type="code" offset="0x10000">dsmusic.dat</rom>
			<rom type="code" offset="0x20000">dsmuspcm.dat</rom>
		</romlist>
		<titlelist>
			<title code="0x11">Opening</title>
			<title code="0x01">Sea</title>
			<title code="0x02">The Paleozoic Era</title>
			<title code="0x0f">Boss A</title>
			<title code="0x16">Boss Clear</title>
			<title code="0x04">Volcano</title>
			<title code="0x19">Boss B</title>
			<title code="0x05">Jungle</title>
			<title code="0x1a">Boss C</title>
			<title code="0x06">Grave Yard</title>
			<title code="0x08">Cave Road</title>
			<title code="0x09">Glacier Land</title>
			<title code="0x0a">Deep Sea</title>
			<title code="0x0b">Dark Quarters</title>
			<title code="0x0c">Dark Castle 1</title>
			<title code="0x0d">Dark Castle 2</title>
			<title code="0x0e">Dark Castle 3</title>
			<title code="0x10">Yamata</title>
			<title code="0x07">Zawell</title>
			<title code="0x15">Alicia</title>
			<title code="0x7f">Ending</title>
			<title code="0x13">Name 1st</title>
			<title code="0x14">Name 2-5</title>
			<title code="0x18">Continue</title>
			<title code="0x42">Omake 1</title>
			<title code="0x41">Omake 2</title>
			<title code="0x40">Speaker Test</title>
		</titlelist>
	</game>
	<game>
		<name>ボスコニアン (X68000)</name>
		<driver type="generic">x68k</driver>
		<options>
			<option name="opm_mix" value="0xc0"/>
			<option name="pcm_mix" value="0xf0"/>
		</options>
		<romlist archive="bos68snd">
			<rom type="code">bos68.bin</rom>
			<rom type="code" offset="0x10000">music.dat</rom>
			<rom type="code" offset="0x20000">adpcm.dat</rom>
		</romlist>
		<titlelist>
			<title code="0x00">00 STOP</title>
			<title code="0x01">01 GOOD MORNING</title>
			<title code="0x02">02 RED ALERT</title>
			<title code="0x03">03</title>
			<title code="0x04">04 LITTLE WAVE</title>
			<title code="0x05">05 BLAST OFF !!</title>
			<title code="0x06">06 GET "LADY"</title>
			<title code="0x07">07 EXCELLENCE</title>
			<title code="0x08">08 BATTLE WAS GONE</title>
			<title code="0x09">09 DUSK...</title>
			<title code="0x0a">0a SPACE HIBABANGO</title>
			<title code="0x0b">0b</title>
			<title code="0x0c">0c</title>
			<title code="0x0d">0d</title>
			<title code="0x0e">0e BLAST POWER !</title>
			<title code="0x0f">0f FLASH FLASH FLASH</title>
			<title code="0x10">10 ASTEROID MEMORY</title>
			<title code="0x11">11</title>
			<title code="0x12">12</title>
			<title code="0x13">13</title>
			<title code="0x14">14</title>
			<title code="0x15">15</title>
			<title code="0x16">16</title>
			<title code="0x17">17</title>
			<title code="0x18">18</title>
			<title code="0x19">19</title>
			<title code="0x1a">1a</title>
		</titlelist>
	</game>
	<game>
		<name>アルガーナ (X68000)</name>
		<driver type="generic">x68k</driver>
		<options>
			<option name="opm_mix" value="0xc0"/>
			<option name="pcm_mix" value="0xf0"/>
		</options>
		<romlist archive="alg68snd">
			<rom type="code">alg_mus.bin</rom>
			<rom type="code" offset="0x10000">alg_mus.mdt</rom>
			<rom type="code" offset="0x20000">alg_mus.smp</rom>
		</romlist>
		<titlelist>
			<title code="0x00">00</title>
			<title code="0x01">01</title>
			<title code="0x02">02</title>
			<title code="0x03">03</title>
			<title code="0x04">04</title>
			<title code="0x05">05</title>
			<title code="0x06">06</title>
			<title code="0x07">07</title>
			<title code="0x08">08</title>
			<title code="0x09">09</title>
			<title code="0x0a">0a</title>
			<title code="0x0b">0b</title>
			<title code="0x0c">0c</title>
			<title code="0x0d">0d</title>
			<title code="0x0e">0e</title>
			<title code="0x0f">0f</title>
			<title code="0x10">10</title>
			<title code="0x11">11</title>
			<title code="0x12">12</title>
			<title code="0x13">13</title>
			<title code="0x14">14</title>
			<title code="0x15">15</title>
			<title code="0x16">16</title>
			<title code="0x17">17</title>
			<title code="0x18">18</title>
			<title code="0x19">19</title>
			<title code="0x1a">1a</title>
			<title code="0x1b">1b</title>
			<title code="0x1c">1c</title>
			<title code="0x1d">1d</title>
			<title code="0x1e">1e</title>
			<title code="0x1f">1f</title>
			<title code="0x20">20</title>
			<title code="0x21">21</title>
			<title code="0x22">22</title>
			<title code="0x23">23</title>
			<title code="0x24">24</title>
			<title code="0x25">25</title>
			<title code="0x26">26</title>
			<title code="0x27">27</title>
			<title code="0x28">28</title>
			<title code="0x29">29</title>
			<title code="0x2a">2a</title>
			<title code="0x2b">2b</title>
			<title code="0x2c">2c</title>
			<title code="0x2d">2d</title>
			<title code="0x2e">2e</title>
			<title code="0x2f">2f</title>
		</titlelist>
	</game>
	<game>
		<name>Fantasy Zone (X68000)</name>
		<driver type="generic">x68k</driver>
		<options>
			<option name="opm_mix" value="0xc0"/>
			<option name="pcm_mix" value="0xf0"/>
		</options>
		<romlist archive="fz68snd">
			<rom type="code">fzmusdrv.bin</rom>
			<rom type="code" offset="0x20000">fzmusic.mus</rom>
			<rom type="code" offset="0x30000">fzmusic.pcm</rom>
		</romlist>
		<titlelist>
			<title code="0x1b">OPA-OPA!</title>
			<!-- <title code="0x39">OPA-OPA!</title> -->
			<title code="0x44">KEEP ON THE BEAT</title>
			<title code="0x3f">SAARI</title>
			<title code="0x41">PROME</title>
			<title code="0x43">HOT SNOW (USA)</title>
			<title code="0x45">HOT SNOW (JPN)</title>
			<title code="0x40">DON'T STOP</title>
			<title code="0x42">DREAMING TOMORROW</title>
			<title code="0x11">BOSS</title>
			<title code="0x3c">YA.DA.YO</title>
			<!-- <title code="0x3d">YA.DA.YO</title> -->
			<title code="0x0f">VICTORY WAY</title>
			<title code="0x20">SHOP</title>
			<title code="0x19">ROUND CLEAR</title>
			<title code="0x1a">GAME OVER</title>
			<title code="0x60">SPACE HARRIER</title>
			<!-- <title code="0x46">SHOP</title> -->
			<title code="0x50">OPA-OPA!          (Arr.)</title>
			<!-- <title code="0x51">OPA-OPA!          (Arr.)</title> -->
			<title code="0x52">KEEP ON THE BEAT  (Arr.)</title>
			<title code="0x53">SAARI             (Arr.)</title>
			<title code="0x54">PROME             (Arr.)</title>
			<title code="0x62">HOT SNOW (USA)    (Arr.)</title>
			<title code="0x55">HOT SNOW (JPN)    (Arr.)</title>
			<title code="0x56">DON'T STOP        (Arr.)</title>
			<title code="0x57">DREAMING TOMORROW (Arr.)</title>
			<title code="0x58">BOSS              (Arr.)</title>
			<title code="0x59">YA.DA.YO          (Arr.)</title>
			<!-- <title code="0x5a">YA.DA.YO          (Arr.)</title> -->
			<title code="0x5d">VICTORY WAY       (Arr.)</title>
			<title code="0x5c">SHOP              (Arr.)</title>
			<title code="0x5b">ROUND CLEAR       (Arr.)</title>
			<!-- <title code="0x5e">VICTORY WAY       (Arr.)</title> -->
			<title code="0x5f">GAME OVER         (Arr.)</title>
			<title code="0x63">THE SUBDUED ZONE</title>
			<title code="0x61">SPACE HARRIER     (Arr.)</title>
			<title code="0x64">???</title>
			<title code="0x00">STOP</title>
			<title code="0xc8">FADE OUT</title>
		</titlelist>
	</game>
	<game>
		<name>Ancient Ys Vanished Omen (X68000)</name>
		<driver type="generic">x68k</driver>
		<options>
			<option name="opm_mix" value="0xc0"/>
			<option name="pcm_mix" value="0xf0"/>
		</options>
		<romlist archive="ys68snd">
			<rom type="code">ys68.bin</rom>
		</romlist>
		<titlelist>
			<title code="0x00">stop</title>
			<title code="0x01">01 Feena</title>
			<title code="0x02">02 Fountain of Love</title>
			<title code="0x03">03 The SYOUNIN</title>
			<title code="0x04">04 Tears of Sylph</title>
			<title code="0x05">05 First Step towards wars</title>
			<title code="0x06">06 Palace</title>
			<title code="0x07">07 Holders of Power</title>
			<title code="0x08">08 Palace of Destruction</title>
			<title code="0x09">09 Beat of the Terror</title>
			<title code="0x0a">10 Tower of the Shadow of Death</title>
			<title code="0x0b">11 The last moment of the Dark</title>
			<title code="0x0c">12 Final Battle</title>
			<title code="0x0d">13 Rest in Peace</title>
			<title code="0x0e">14 The morning grow</title>
			<title code="0x0f">15 See you again</title>
			<title code="0x11">16 (X68000 Original B.G.M 1)</title>
			<title code="0x12">17 (X68000 Original B.G.M 2)</title>
			<title code="0x14">18 Game Over</title>
			<title code="0x16">19 Rest in Peace(Harmonica Ver.)</title>
			<title code="0x36">20 Lucky</title>
			<title code="0x20">SE01</title>
			<title code="0x21">SE02</title>
			<title code="0x22">SE03</title>
			<title code="0x23">SE04</title>
			<title code="0x24">SE05</title>
			<title code="0x25">SE06</title>
			<title code="0x26">SE07</title>
			<title code="0x27">SE08</title>
			<title code="0x28">SE09</title>
			<title code="0x29">SE10</title>
			<title code="0x2a">SE11</title>
			<title code="0x2b">SE12</title>
			<title code="0x2c">SE13</title>
			<title code="0x2d">SE14</title>
			<title code="0x2e">SE15</title>
			<title code="0x2f">SE16</title>
			<title code="0x30">SE17</title>
			<title code="0x31">SE18</title>
			<title code="0x32">SE19</title>